.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "/HOME/YANGPC/SRC" "1" "02/07/2014" "" "Atomic and pointer manipulatio"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"

   /home/yangpc/src/kernel\-taobao\-2.6.32\-279//arch/x86/include/asm/unaligned.h
   \- Document generation inconsistency
.SH "
   OOPS
  "
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBWarning\fR
.PP
The template for this document tried to insert the structured comment from the file
\fI/home/yangpc/src/kernel\-taobao\-2.6.32\-279//arch/x86/include/asm/unaligned.h\fR
at this point, but none was found. This dummy section is inserted to allow generation to continue.
